[package]
name = "controlbridge-receiver"
version = "1.0.0-rc1"
edition = "2024"

[dependencies]
slint = { version = "1.9", features = ["image-default-formats"] }
byteorder = "1.5"
crossbeam-channel = "0.5"
env_logger = "0.11.11"
log = { version = "0.4", features = ["max_level_debug", "release_max_level_info"] }

[target.'cfg(target_os = "windows")'.dependencies]
vigem-client = { version = "0.1.4", features = ["unstable_xtarget_notification"] }

[[bin]]
name = "ControlBridgeReceiver"
path = "src/main.rs"

[build-dependencies]
embed-resource = "3.0.11"
