name = "controlbridge-receiver"
product-name = "ControlBridgeReceiver"
identifier = "io.github.controlbridgereceiver"
version = "1.0.0-rc1"
binaries = [
  { path = "ControlBridgeReceiver", main = true }
]
out-dir = "target/release"
before-packaging-command = "cargo build --release"

icons = [
  "icons/512x512.png"
]

[nsis]
installerIcon = "icons/icon.ico"
installMode = "perMachine"