name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            name: windows-x64
            formats: nsis
            artifact: ControlBridgeReceiver-windows-x86_64
            path: target/release/ControlBridgeReceiver_*.exe

          - os: windows-11-arm
            name: windows-arm64
            formats: nsis
            artifact: ControlBridgeReceiver-windows-arm64
            path: target/release/ControlBridgeReceiver_*.exe

          - os: ubuntu-latest
            name: linux-x64
            formats: appimage
            artifact: ControlBridgeReceiver-linux-x86_64
            path: target/release/ControlBridgeReceiver_*.AppImage

          - os: ubuntu-24.04-arm
            name: linux-arm64
            formats: appimage
            artifact: ControlBridgeReceiver-linux-arm64
            path: target/release/ControlBridgeReceiver_*.AppImage

    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

    - name: Setup Rust toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Setup Cache
      uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2.9.2

    - name: Install system dependencies
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        sudo apt-get update
        sudo apt-get install -y pkg-config libfontconfig1-dev


    - name: Build
      run: cargo install cargo-packager && cargo packager --release --formats ${{ matrix.formats }}

    - name: Upload Build
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
      with:
        name: ${{ matrix.artifact }}
        path: ${{ matrix.path }}
